# Generated by Django 3.0.5 on 2020-04-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_entry', models.DateTimeField(auto_now_add=True, verbose_name='DateTime of entry')),
                ('date_set', models.DateField(verbose_name='Date of set')),
                ('duration', models.FloatField(verbose_name='Duration of set')),
                ('driver', models.TextField(verbose_name='Name of driver')),
                ('rider', models.TextField(verbose_name='Name of rider')),
                ('boat', models.TextField(verbose_name='Boat used')),
            ],
            options={
                'ordering': ['-date_set', 'boat'],
            },
        ),
    ]
