# Generated by Django 3.0.5 on 2020-04-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sets_app', '0003_auto_20200414_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last name')),
                ('nationality', models.CharField(max_length=100, verbose_name='Nationality')),
                ('date_of_birth', models.DateField(verbose_name='Birth date')),
            ],
        ),
    ]
