# Generated by Django 3.0.5 on 2020-04-19 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sets_app', '0004_rider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='rider',
            field=models.ForeignKey(help_text='Select boat used for set', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sets_app.Rider'),
        ),
    ]
