# Generated by Django 3.0.5 on 2020-04-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sets_app', '0005_auto_20200419_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='date_added',
            field=models.DateField(default='2020-04-01', verbose_name='Date boat was added to fleet'),
            preserve_default=False,
        ),
    ]
